// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type FileHash struct {
	Filepath   string
	Crc32      sql.NullString
	Xxhash64   sql.NullString
	Md4        sql.NullString
	Md5        sql.NullString
	Sha1       sql.NullString
	Sha256     sql.NullString
	Sha512     sql.NullString
	Blake2b256 sql.NullString
	Blake2b512 sql.NullString
	Blake3     sql.NullString
	Sha3224    sql.NullString
	Sha3256    sql.NullString
	Sha3384    sql.NullString
	Sha3512    sql.NullString
	Ed2k       sql.NullString
	Size       int64
	Mtime      interface{}
}
